<!doctype html>
<html>
<head>
  <title>Twico</title>
  <meta charset="utf-8"/>
  <meta name="keywords" content="Twico, Tweet, Conference, Events, Twitter" />
  <meta name="description" content="Tweet your conference as you should..." />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" type="text/css" href="/css/html.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/css/layout.css" media="screen" />
  <?php echo $this->headLink()?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script type="text/javascript">
        !window.jQuery && document.write("<script type='text/javascript' src='/js/jquery.js'><\/script>");
  </script>
  <?php echo $this->headScript()?>
</head>

<body>
<!-- #wrapper: centers the content and sets the width -->
<div id="wrapper">
  <!-- #content: applies the white, dropshadow background -->
  <div id="content">
    <!-- #header: holds site title and subtitle -->
    <div style="margin-left:20px" id="header">
        <h1><img width="100px" align="top" src="/img/hashtag.jpg" alt="hashtag"/><span style="font-size:120px" class="twicoLogo">Twico</span><span>.at</span></h1>
      <p style="margin-left:130px">Tweet your conference as you should...</p>
      <div style="margin:110px">
          <a href="/services/twitter/do/redirect"/><img style="border:0px" alt="Sign in with Twitter (Lighter Style)" src="//si0.twimg.com/images/dev/buttons/sign-in-with-twitter-l.png"/></a>
      </div>  
    </div>
    <div id="page">
        <p class="footer">by <a href="http://twitter.com/AV4TAr" target="_blank">@AV4TAr</a> & <a href="http://twitter.com/jorgesierra" target="_blank">@jorgesierra</a></p>
    </page>
  </div>
</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1859862-16']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

