
<p><input type="text" id="new_htag"/><a href="#" id="add_new_htag">Add</a></p>
<h1>My hashtags</h1>
<div id="my_hastags_conteiner"></div>
<script type="text/javascript">
    $(document).ready(function(){
        
        function updateMyList(){
            $.getJSON('/my-hashtags/list/?format=json', function(data) {
                var items = [];
                $.each(data.myHashTags, function(key, val) {
                    items.push('<li id="' + val.id + '"><a href="/#' + val.hashtag + '">' + val.hashtag + '</a></li>');
                  });
                var new_ul =  $('<ul/>', {
                    'class': 'hashtags-list',
                    html: items.join('')
                  });
                $('#my_hastags_conteiner').html(new_ul);
            });
        }
        
        updateMyList();
        
        $('#add_new_htag').click(function(){
            var new_htag = $("#new_htag").val();
            if(new_htag != ""){
                $.post("/my-hashtags/new/?format=json", {new_hast_tag:new_htag}, function(data){
                    if(data.error){
                        alert(data.error)
                    } else {
                        $("#new_htag").val('');
                        updateMyList();
                    }
                })
            }
        });

       
    });
</script>