<!doctype html>
<html>
<head>
  <title>Twico</title>
  <meta charset="utf-8"/>
  <meta name="keywords" content="Twico, Tweet, Conference, Events, Twitter" />
  <meta name="description" content="Usable user interface to tweet events" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" type="text/css" href="/css/html.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="/css/layout.css" media="screen" />
  <?php echo $this->headLink()?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script type="text/javascript">
        !window.jQuery && document.write("<script type='text/javascript' src='/js/jquery.js'><\/script>");
  </script>
  <?php echo $this->headScript()?>
</head>

<body>
<!-- #wrapper: centers the content and sets the width -->
<div id="wrapper">
  <!-- #content: applies the white, dropshadow background -->
  <div id="content">
    <!-- #header: holds site title and subtitle -->
    <div id="header">
      <h1><span class="twicoLogo">Twico.at </span><script type="text/javascript">document.write(location.hash)</script></h1>
    </div>
    <div id="page">
        <?php echo $this->layout ()->content;?>
      <p class="footer"><a href="/logout">Logout</a> | <a href="/my-hashtags">#My Hastags</a></p>
    </div>
  </div>
</div>
<script type='text/javascript' src="/js/script.js"></script>
</body>
</html>